version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  post_build:
    commands:
      - mvn package
      - mv target/MobileEnrollment.war MobileEnrollment.war
artifacts:
  files:
    - my-web-app.war
    - .ebextensions/**/*
  base-directory: 'target/MobileEnrollment'
